name: ci_app
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Setup project
      - run: make setup
      # Start project
      - run: make start
      # Test project
      - run: make test
      # Lint project
      - run: make lint